apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: greenbone-prod
namePrefix: prod-
commonLabels:
  app: notus-scanner
  environment: prod

resources:
- ../../../../base

components:
- ../../base
#- ../../../../../../variants/notus-scanner/prod/openshift/te
  

images:
- name: greenbone/notus-scanner
  newTag: "stable"

replicas:
- count: 1
  name: notus-scanner