apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: greenbone-prod
namePrefix: prod-
commonLabels:
  app: gvm-tools
  environment: prod

resources:
- ../../../../base

components:
- ../../base
#- ../../../../../../variants/gvm-tools/prod/openshift/te
  

images:
- name: greenbone/gvm-tools
  newTag: "latest"

replicas:
- count: 1
  name: gvm-tools