apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches: 

   
  ### DEPLOYMENT RESOURCES ###
  - target:
      kind: Deployment
      name: pg-gvm
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 150m
  - target:
      kind: Deployment
      name: pg-gvm
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

#  ### VOLUMES ###
  - target:
      kind: Deployment
      name: pg-gvm
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: prod-psql-data-vol
  - target:
      kind: Deployment
      name: pg-gvm
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1/persistentVolumeClaim/claimName
        value: prod-psql-socket-vol


