apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: greenbone-prod
namePrefix: prod-
commonLabels:
  app: data-objects
  environment: prod

resources:
- ../../../../base

components:
- ../../base
#- ../../../../../../variants/data-objects/prod/openshift/te
- ../../../../../../common/prod/openshift/
  

images:
- name: greenbone/data-objects
  newTag: "latest"

replicas:
- count: 1
  name: data-objects