apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-formats
spec:
  selector:
    matchLabels:
      app: report-formats
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: report-formats
    spec:
      containers:
      - name: report-formats
        image: greenbone/report-formats
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File       
        volumeMounts:
            - mountPath: /mnt
              name: report-formats-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: report-formats-vol
          persistentVolumeClaim:
            claimName: data-objects-vol


