apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches: 

   
  ### DEPLOYMENT RESOURCES ###
  - target:
      kind: Deployment
      name: mqtt-broker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 150m
  - target:
      kind: Deployment
      name: mqtt-broker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi



  ### IMAGE PULL SECRETS
  - target:
      kind: Deployment
      name: mqtt-broker
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: prod-gitlab-docker-registry
