apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: greenbone-prod
namePrefix: prod-
commonLabels:
  app: mqtt-broker
  environment: prod

resources:
- ../../../../base

components:
- ../../base
#- ../../../../../../variants/mqtt-broker/prod/openshift/te
  

images:
- name: greenbone/mqtt-broker
  newTag: "latest"

replicas:
- count: 1
  name: mqtt-broker