apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: greenbone-prod
namePrefix: prod-
commonLabels:
  app: pg-gvm
  environment: prod

resources:
- ../../../../base

components:
- ../../base
#- ../../../../../../variants/pg-gvm/prod/openshift/te
- ../../../../../../common/prod/openshift/
  

images:
- name: greenbone/pg-gvm
  newTag: "stable"

replicas:
- count: 1
  name: pg-gvm