apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-objects
spec:
  selector:
    matchLabels:
      app: data-objects
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data-objects
    spec:
      containers:
      - name: data-objects
        image: greenbone/data-objects
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File       
        volumeMounts:
            - mountPath: /
              name: data-objects-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-objects-vol
          persistentVolumeClaim:
            claimName: data-objects-vol


