apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches: 

   
  ### DEPLOYMENT RESOURCES ###
  - target:
      kind: Deployment
      name: ospd-openvas
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 150m
  - target:
      kind: Deployment
      name: ospd-openvas
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

#  ### VOLUMES ###
  - target:
      kind: Deployment
      name: ospd-openvas
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: prod-gpg-data-vol
  - target:
      kind: Deployment
      name: ospd-openvas
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1/persistentVolumeClaim/claimName
        value: prod-vt-data-vol
  - target:
      kind: Deployment
      name: ospd-openvas
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/2/persistentVolumeClaim/claimName
        value: prod-notus-data-vol
  - target:
      kind: Deployment
      name: ospd-openvas
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/3/persistentVolumeClaim/claimName
        value: prod-ospd-openvas-socket-vol
  - target:
      kind: Deployment
      name: ospd-openvas
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/4/persistentVolumeClaim/claimName
        value: prod-redis-socket-vol


