apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: greenbone-prod
namePrefix: prod-
commonLabels:
  app: gsa
  environment: prod

resources:
- ../../../../base

components:
- ../../base
#- ../../../../../../variants/gsa/prod/openshift/te
  

images:
- name: greenbone/gsa
  newTag: "stable"

replicas:
- count: 1
  name: gsa