apiVersion: apps/v1
kind: Deployment
metadata:
  name: scap-data
spec:
  selector:
    matchLabels:
      app: scap-data
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scap-data
    spec:
      containers:
      - name: scap-data
        image: greenbone/scap-data
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File       
        volumeMounts:
            - mountPath: /mnt
              name: scap-data-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: scap-data-vol
          persistentVolumeClaim:
            claimName: scap-data-vol


