---
apiVersion: v1
kind: Service
metadata: 
  name: ospd-openvas
spec:
  ports:
  - name: 9392-tcp
    port: 9392
    protocol: TCP
    targetPort: 9392
  selector:
    app: ospd-openvas
  sessionAffinity: None
  type: ClusterIP
 
