apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: greenbone-prod
namePrefix: prod-
commonLabels:
  app: dfn-cert-data
  environment: prod

resources:
- ../../../../base

components:
- ../../base
#- ../../../../../../variants/dfn-cert-data/prod/openshift/te
  

images:
- name: greenbone/dfn-cert-data
  newTag: "latest"

replicas:
- count: 1
  name: dfn-cert-data