apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerability-tests
spec:
  selector:
    matchLabels:
      app: vulnerability-tests
  replicas: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vulnerability-tests
    spec:
      containers:
      - name: vulnerability-tests
        image: greenbone/vulnerability-tests
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File       
        volumeMounts:
            - mountPath: /mnt
              name: vt-data-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vt-data-vol
          persistentVolumeClaim:
            claimName: vt-data-vol


