apiVersion: apps/v1
kind: Deployment
metadata:
  name: notus-scanner
spec:
  selector:
    matchLabels:
      app: notus-scanner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notus-scanner
    spec:
      containers:
      - name: notus-scanner        
        env:          
          - name: NOTUS_SCANNER_MQTT_BROKER_ADDRESS
            value: 'mqtt-broker'          
          - name: NOTUS_SCANNER_PRODUCTS_DIRECTORY
            value: '/var/lib/notus/products'